# Use root/example as user/password credentials
version: '3.1'

services:

  mydatabases:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Megamanx1
      MYSQL_DATABASE: mydbclass
      MYSQL_USER: mydbuser
      MYSQL_PASSWORD: Absa
    ports:
      - 3889:3306
